#!/bin/bash
awk -i inplace -i "utils.awk" '
{
    if ($0 ~ "{{begin-newsitem") {
        time = get_parameter($0, "time")
        if (time != "") {
            sub("T", " ", time)
            sub("Z", "",  time)
            split(time, arr, " ")
            date = arr[1]
            datetimestr = arr[1] " " arr[2] " UTC"
        } else {
            datetimestr = get_parameter($0, "date")
        }

        sub("{{begin-newsitem", "{{begin-newsitem |datetimestr=" datetimestr " |date=" date, $0)
    }
    print $0
}
' "$1"
